swagger: 2.0
info:
  title: Test Title
  version: 1.0
paths:
  '/campaigns':
    get:
      responses:
        200:
          description: Get a list of campaigns
          headers:
            X-Rate-Limit-Limit:
              type: integer
              description: The number of allowed requests in a period
              minimum: 0
              maximum: 300 
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              address:
                type: string
              age:
                type: integer
                minimum: 0
              details:
                $ref: '#/definitions/Details'


